name: pypressruby-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6.0
  - numpy
  - pip
  - sphinx
  - pytest
  - pytest-cov
  - flake8
  - lmfit
  - versioneer
  - pyqt
  - seabreeze
  - matplotlib
  - pip:
    - ipython-genutils==0.2.0
    - prompt-toolkit==1.0.15
    - sphinx-rtd-theme
    - super-state-machine
    - black
